services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8000"
    env_file:
      - ".env.example"
    volumes:
      - .:/app
    networks:
      - pad 
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=pad
      - POSTGRES_DB=pad
    volumes:
      - pad_db:/var/lib/postgresql/data
    networks:
      - pad

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - pad

volumes:
  pad_db:

networks:
  pad:
