SHELL := /bin/sh

install:
	poetry install

activate:
	poetry shell

run:
	python manage.py runserver

shell:
	python manage.py shell

migration:
	python manage.py makemigrations

migrate:
	python manage.py migrate

superuser:
	python manage.py createsuperuser

collectstatic:
	python manage.py collectstatic