import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const googleSans = localFont({
  src: [
    {
      path: '../public/fonts/GoogleSans-Regular.ttf',
      weight: '400'
    },
    {
      path: '../public/fonts/GoogleSans-Bold.ttf',
      weight: '700'
    },
    {
      path: '../public/fonts/GoogleSans-Medium.ttf',
      weight: '500'
    }
  ],
  variable: '--font-google'
})

export const metadata: Metadata = {
  title: "Passkey Abdication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
